[package]
name = "teraron"
version = "0.0.1"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/rust-analyzer/teraron"
description = "Genrate Rust code from a .tera template and a .ron data"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
tera = "0.11.18"
ron = "0.4.0"
heck = "0.3.0"
